### PR TITLE
Fix bug when generating en nodes.

### PR DESCRIPTION
**Pull request by amodia**
Hi @aronasorman I a found bug when generating en nodes. This will fix #30

### CODE REVIEW

**Comment by aronasorman** [comment]
What's the exact bug here?

**Comment by amodia** [comment]
When I generate xh language pack the en_node.json file is empty because the `url` variable is not updated with the en lang code.

**Comment by amodia** [comment]
I mean this variable `url = lang_url.format(projection=json.dumps(projection), lang=lang)`

**Comment by amodia** [comment]
@aronasorman I'm done testing on generating language packs. So far these are the list of bug and enhancement that I fix.

Bug:
- Generate xh language packs will result of empty en_nodes.json file. Because the `url` variable is not updated with the new language code. 

Enhancement:
- Create a reusable en lang code variable.
- Check if language code available in dubbed videos mappings.

**Pull request merged**
